// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentinelAI.Infrastructure.Data;

#nullable disable

namespace SentinelAI.Infrastructure.Migrations
{
    [DbContext(typeof(SentinelDbContext))]
    [Migration("20260730102028_ConfigureEntitiesAndEnums")]
    partial class ConfigureEntitiesAndEnums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SentinelAI.Domain.Models.Chain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HopCount")
                        .HasColumnType("int");

                    b.Property<string>("MinConfidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId");

                    b.ToTable("Chains");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ChainHop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BlueValidated")
                        .HasColumnType("bit");

                    b.Property<Guid>("ChainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EdgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HopOrder")
                        .HasColumnType("int");

                    b.Property<string>("TechniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.HasIndex("EdgeId");

                    b.HasIndex("FindingId");

                    b.ToTable("ChainHops");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Citation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChainHopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnowledgeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChainHopId");

                    b.HasIndex("ReportId");

                    b.ToTable("Citations");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CveId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CweId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Redacted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("SourceTool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("OrientedAttackDir")
                        .HasColumnType("bit");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Seam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("ScanJobId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("GraphEdges");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attrs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHot")
                        .HasColumnType("bit");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId", "NodeKey")
                        .IsUnique();

                    b.ToTable("GraphNodes");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubInstallationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackSlot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Retained")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.RuleMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CveId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CweId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceTool")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SourceTool", "CheckId")
                        .IsUnique();

                    b.ToTable("RuleMappings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f099c288-0f0c-43f1-b956-f6a6233ba3eb"),
                            CheckId = "SCS0028",
                            CweId = "CWE-502",
                            Notes = "Baseline exact lookup map",
                            SourceTool = "roslyn"
                        },
                        new
                        {
                            Id = new Guid("b882650b-47e1-4c07-ba96-7fc3b8a13a21"),
                            CheckId = "CKV_AWS_20",
                            CweId = "CWE-284",
                            Notes = "Baseline exact lookup map",
                            SourceTool = "checkov"
                        });
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ScanBundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactManifest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IngressRedactionApplied")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RunnerSecretScan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScannerVersions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId")
                        .IsUnique();

                    b.ToTable("ScanBundles");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BundlePurged")
                        .HasColumnType("bit");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorpusVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TriggeredBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TriggeringUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TriggeringUserId");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Chain", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithMany("Chains")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ChainHop", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.Chain", "Chain")
                        .WithMany("ChainHops")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SentinelAI.Domain.Models.GraphEdge", "Edge")
                        .WithMany("ChainHops")
                        .HasForeignKey("EdgeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SentinelAI.Domain.Models.Finding", "Finding")
                        .WithMany("ChainHops")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chain");

                    b.Navigation("Edge");

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Citation", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ChainHop", "ChainHop")
                        .WithMany("Citations")
                        .HasForeignKey("ChainHopId");

                    b.HasOne("SentinelAI.Domain.Models.Report", "Report")
                        .WithMany("Citations")
                        .HasForeignKey("ReportId");

                    b.Navigation("ChainHop");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Finding", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithMany("Findings")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphEdge", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.GraphNode", "FromNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithMany("GraphEdges")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentinelAI.Domain.Models.GraphNode", "ToNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ScanJob");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphNode", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithMany("GraphNodes")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Project", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.Tenant", "Tenant")
                        .WithMany("Projects")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Report", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithOne("Report")
                        .HasForeignKey("SentinelAI.Domain.Models.Report", "ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ScanBundle", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithOne("ScanBundle")
                        .HasForeignKey("SentinelAI.Domain.Models.ScanBundle", "ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ScanJob", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.Project", "Project")
                        .WithMany("ScanJobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentinelAI.Domain.Models.User", "TriggeringUser")
                        .WithMany("TriggeredJobs")
                        .HasForeignKey("TriggeringUserId");

                    b.Navigation("Project");

                    b.Navigation("TriggeringUser");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.User", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Chain", b =>
                {
                    b.Navigation("ChainHops");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ChainHop", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Finding", b =>
                {
                    b.Navigation("ChainHops");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphEdge", b =>
                {
                    b.Navigation("ChainHops");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Project", b =>
                {
                    b.Navigation("ScanJobs");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Report", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ScanJob", b =>
                {
                    b.Navigation("Chains");

                    b.Navigation("Findings");

                    b.Navigation("GraphEdges");

                    b.Navigation("GraphNodes");

                    b.Navigation("Report");

                    b.Navigation("ScanBundle");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Tenant", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.User", b =>
                {
                    b.Navigation("TriggeredJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
