// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentinelAI.Infrastructure.Data;

#nullable disable

namespace SentinelAI.Infrastructure.Migrations
{
    [DbContext(typeof(SentinelDbContext))]
    [Migration("20260805092840_SeedRuleMappings")]
    partial class SeedRuleMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SentinelAI.Domain.Models.Chain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HopCount")
                        .HasColumnType("int");

                    b.Property<string>("MinConfidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId");

                    b.HasIndex("TenantId");

                    b.ToTable("Chains");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ChainHop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BlueValidated")
                        .HasColumnType("bit");

                    b.Property<Guid>("ChainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EdgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HopOrder")
                        .HasColumnType("int");

                    b.Property<string>("TechniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.HasIndex("EdgeId");

                    b.HasIndex("FindingId");

                    b.HasIndex("TenantId");

                    b.ToTable("ChainHops");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Citation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChainHopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnowledgeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChainHopId");

                    b.HasIndex("ReportId");

                    b.HasIndex("TenantId");

                    b.ToTable("Citations");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CveId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CweId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Redacted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("SourceTool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId");

                    b.HasIndex("TenantId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("OrientedAttackDir")
                        .HasColumnType("bit");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Seam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("ScanJobId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("GraphEdges");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attrs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHot")
                        .HasColumnType("bit");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ScanJobId", "NodeKey")
                        .IsUnique();

                    b.ToTable("GraphNodes");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubInstallationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackSlot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Framing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Retained")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.RuleMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CveId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CweId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceTool")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SourceTool", "CheckId")
                        .IsUnique();

                    b.ToTable("RuleMappings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f099c288-0f0c-43f1-b956-f6a6233ba3eb"),
                            CheckId = "SCS0028",
                            CweId = "CWE-502",
                            Notes = "Baseline exact lookup map",
                            SourceTool = "roslyn"
                        },
                        new
                        {
                            Id = new Guid("20d42173-70fa-4d33-acde-0fca5d4acb42"),
                            CheckId = "SCS0001",
                            CweId = "CWE-78",
                            Notes = "Security Code Scan rule catalogue: command injection",
                            SourceTool = "roslyn"
                        },
                        new
                        {
                            Id = new Guid("dd4f560a-16cc-462e-91d3-da21cf70de3e"),
                            CheckId = "SCS0005",
                            CweId = "CWE-338",
                            Notes = "Security Code Scan rule catalogue: weak random number generator",
                            SourceTool = "roslyn"
                        },
                        new
                        {
                            Id = new Guid("7853dced-5fc7-4263-b765-8d0b2d72636e"),
                            CheckId = "SCS0018",
                            CweId = "CWE-22",
                            Notes = "Security Code Scan rule catalogue: path traversal",
                            SourceTool = "roslyn"
                        },
                        new
                        {
                            Id = new Guid("b827ed21-2d56-47bd-a7c2-b9e0153d9cfc"),
                            CheckId = "SCS0026",
                            CweId = "CWE-89",
                            Notes = "Security Code Scan rule catalogue: SQL injection",
                            SourceTool = "roslyn"
                        },
                        new
                        {
                            Id = new Guid("29eea3df-8e2d-4e22-8d75-a85bfa5683d3"),
                            CheckId = "SCS0029",
                            CweId = "CWE-79",
                            Notes = "Security Code Scan rule catalogue: cross-site scripting",
                            SourceTool = "roslyn"
                        },
                        new
                        {
                            Id = new Guid("b882650b-47e1-4c07-ba96-7fc3b8a13a21"),
                            CheckId = "CKV_AWS_20",
                            CweId = "CWE-284",
                            Notes = "Baseline exact lookup map",
                            SourceTool = "checkov"
                        },
                        new
                        {
                            Id = new Guid("1b276ae3-0480-42a5-8449-a79a0ab218ab"),
                            CheckId = "CKV_AWS_18",
                            CweId = "CWE-778",
                            Notes = "Checkov policy catalogue: S3 access logging not enabled",
                            SourceTool = "checkov"
                        },
                        new
                        {
                            Id = new Guid("421bbdc3-84c3-4ef7-9b24-76bb0092e491"),
                            CheckId = "CKV_AWS_19",
                            CweId = "CWE-311",
                            Notes = "Checkov policy catalogue: S3 not encrypted at rest",
                            SourceTool = "checkov"
                        },
                        new
                        {
                            Id = new Guid("790afc1c-f4ea-46e8-989d-17176ab8f9a9"),
                            CheckId = "CKV_AWS_24",
                            CweId = "CWE-284",
                            Notes = "Checkov policy catalogue: security group allows ingress from 0.0.0.0/0 to port 22",
                            SourceTool = "checkov"
                        },
                        new
                        {
                            Id = new Guid("eef61ee4-2167-4f09-873a-8e30c5250145"),
                            CheckId = "CKV_DOCKER_3",
                            CweId = "CWE-250",
                            Notes = "Checkov policy catalogue: container has no non-root user",
                            SourceTool = "checkov"
                        },
                        new
                        {
                            Id = new Guid("d62d3bff-5cea-408e-83b4-1a73c83b834d"),
                            CheckId = "AVD-AWS-0086",
                            CweId = "CWE-284",
                            Notes = "Trivy AVD misconfiguration catalogue: S3 public access block missing",
                            SourceTool = "trivy"
                        },
                        new
                        {
                            Id = new Guid("1daf0baa-6a14-4f71-9dda-9841409f10ee"),
                            CheckId = "AVD-AWS-0089",
                            CweId = "CWE-778",
                            Notes = "Trivy AVD misconfiguration catalogue: S3 bucket access logging disabled",
                            SourceTool = "trivy"
                        });
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ScanBundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactManifest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IngressRedactionApplied")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RunnerSecretScan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScannerVersions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageLocator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScanJobId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("ScanBundles");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BundlePurged")
                        .HasColumnType("bit");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorpusVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelTierHint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RetainReport")
                        .HasColumnType("bit");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TriggeredBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TriggeringUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TriggeringUserId");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Chain", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithMany("Chains")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ChainHop", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.Chain", "Chain")
                        .WithMany("ChainHops")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SentinelAI.Domain.Models.GraphEdge", "Edge")
                        .WithMany("ChainHops")
                        .HasForeignKey("EdgeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SentinelAI.Domain.Models.Finding", "Finding")
                        .WithMany("ChainHops")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chain");

                    b.Navigation("Edge");

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Citation", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ChainHop", "ChainHop")
                        .WithMany("Citations")
                        .HasForeignKey("ChainHopId");

                    b.HasOne("SentinelAI.Domain.Models.Report", "Report")
                        .WithMany("Citations")
                        .HasForeignKey("ReportId");

                    b.Navigation("ChainHop");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Finding", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithMany("Findings")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphEdge", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.GraphNode", "FromNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithMany("GraphEdges")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentinelAI.Domain.Models.GraphNode", "ToNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ScanJob");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphNode", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithMany("GraphNodes")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Project", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.Tenant", "Tenant")
                        .WithMany("Projects")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Report", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithOne("Report")
                        .HasForeignKey("SentinelAI.Domain.Models.Report", "ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ScanBundle", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.ScanJob", "ScanJob")
                        .WithOne("ScanBundle")
                        .HasForeignKey("SentinelAI.Domain.Models.ScanBundle", "ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ScanJob", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.Project", "Project")
                        .WithMany("ScanJobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentinelAI.Domain.Models.User", "TriggeringUser")
                        .WithMany("TriggeredJobs")
                        .HasForeignKey("TriggeringUserId");

                    b.Navigation("Project");

                    b.Navigation("TriggeringUser");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.User", b =>
                {
                    b.HasOne("SentinelAI.Domain.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Chain", b =>
                {
                    b.Navigation("ChainHops");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ChainHop", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Finding", b =>
                {
                    b.Navigation("ChainHops");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphEdge", b =>
                {
                    b.Navigation("ChainHops");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.GraphNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Project", b =>
                {
                    b.Navigation("ScanJobs");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Report", b =>
                {
                    b.Navigation("Citations");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.ScanJob", b =>
                {
                    b.Navigation("Chains");

                    b.Navigation("Findings");

                    b.Navigation("GraphEdges");

                    b.Navigation("GraphNodes");

                    b.Navigation("Report");

                    b.Navigation("ScanBundle");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.Tenant", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SentinelAI.Domain.Models.User", b =>
                {
                    b.Navigation("TriggeredJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
